"""add peer table

Revision ID: 64dbc0991bae
Revises: 583d3cfa0c78
Create Date: 2022-01-24 13:40:24.695669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dbc0991bae'
down_revision = '583d3cfa0c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_public_key'), 'peer', ['public_key'], unique=False)
    op.add_column('message', sa.Column('address', sa.LargeBinary(), nullable=True))
    op.add_column('message', sa.Column('payload', sa.Text(), nullable=False))
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('message', 'payload')
    op.drop_column('message', 'address')
    op.drop_index(op.f('ix_peer_public_key'), table_name='peer')
    op.drop_table('peer')
    # ### end Alembic commands ###
